# Setup
title:        Log4jdbc-log4j2
tagline:      JDBC proxy driver for logging SQL and other interesting information.
baseurl:      "/"
paginate:     1

# About/contact
author:
  name:       Bruno Rozendo
  url:        http://brunorozendo.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown